-- Registro persistente de las tandas de avisos por mail (cancelacion de salida):
-- guarda cuando se envio, cuantos salieron y a quienes fallo, para poder
-- auditarlo desde el panel (los logs de runtime de Vercel se borran a la hora).
-- Ejecutar una vez en el SQL Editor de Supabase (es idempotente).

CREATE TABLE IF NOT EXISTS tourist_notification_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  departure_id BIGINT REFERENCES tourist_departures (id) ON DELETE CASCADE,
  kind TEXT NOT NULL DEFAULT 'departure_cancelled',
  channel TEXT NOT NULL DEFAULT 'email',
  reason TEXT,
  total INTEGER NOT NULL DEFAULT 0,
  sent INTEGER NOT NULL DEFAULT 0,
  failed INTEGER NOT NULL DEFAULT 0,
  -- [{ booking_id, name, email, ok, error? }]
  recipients JSONB NOT NULL DEFAULT '[]'::jsonb
);

CREATE INDEX IF NOT EXISTS idx_tourist_notification_logs_departure
  ON tourist_notification_logs (departure_id, created_at DESC);

-- RLS sin politicas: solo accede el backend con la service key (patron del repo).
ALTER TABLE tourist_notification_logs ENABLE ROW LEVEL SECURITY;
