-- Guia del recorrido en los books de fotos (pedido de la Direccion de Turismo,
-- 2026-09-07): cada book registra que guia hizo el recorrido, y ademas queda
-- un registro historico PERMANENTE en tour_guide_log para poder contar cuantos
-- recorridos hizo cada guia (los books en si se borran a los 7 dias por el
-- cron de limpieza; el log no se borra nunca).
-- Ejecutar una vez en el SQL Editor de Supabase (es idempotente).

ALTER TABLE photo_books
  ADD COLUMN IF NOT EXISTS guide_name TEXT;

-- Cantidad de personas que participaron del recorrido (pedido de Mariana,
-- 2026-09-07): la carga el guia junto con su nombre al crear el book.
ALTER TABLE photo_books
  ADD COLUMN IF NOT EXISTS people_count INTEGER;

CREATE TABLE IF NOT EXISTS tour_guide_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  -- Si el book se borra (limpieza o a mano), el registro queda con book_id NULL.
  book_id UUID REFERENCES photo_books(id) ON DELETE SET NULL,
  tour_date DATE NOT NULL,
  title TEXT NOT NULL,
  guide_name TEXT NOT NULL
);

ALTER TABLE tour_guide_log
  ADD COLUMN IF NOT EXISTS people_count INTEGER;

CREATE INDEX IF NOT EXISTS idx_tour_guide_log_guide ON tour_guide_log (guide_name);
-- Un registro por book mientras el book exista (permite upsert al editar).
CREATE UNIQUE INDEX IF NOT EXISTS idx_tour_guide_log_book
  ON tour_guide_log (book_id) WHERE book_id IS NOT NULL;

ALTER TABLE tour_guide_log ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "service_role_full_access_tour_guide_log" ON tour_guide_log;
CREATE POLICY "service_role_full_access_tour_guide_log" ON tour_guide_log
  FOR ALL USING (auth.role() = 'service_role');
